services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: front
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_API_TOKEN=${VITE_API_TOKEN}
    ports:
      - "80:80"
